[project]
name = "bp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "luyijingning", email = "2182716481@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
bp = "bp:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
